import React from 'react'

import { makeStyles } from '@material-ui/core/styles'
import Typography from '@material-ui/core/Typography'
import List from '@material-ui/core/List'
import ListItem from '@material-ui/core/ListItem'
import ListItemText from '@material-ui/core/ListItemText'

// import { HubConnection } from '@aspnet/signalr'
// import * as signalR from '@aspnet/signalr'

// import axios from 'axios'

const useStyles = makeStyles((theme) => ({
  text: {
    padding: theme.spacing(2, 2, 0),
  },
  paper: {
    paddingBottom: 50,
  },
  list: {
    marginBottom: theme.spacing(2),
  },
  appBar: {
    top: 'auto',
    bottom: 0,
  },
  grow: {
    flexGrow: 1,
  },
}))

export default function Chat({ nick, message, messages }) {
  messages = [
    {
      message:
        'My appointment for the doctor was rescheduled for next Saturday.',
      person: 'Nado',
    },
    {
      message:
        'My appointment for the doctor was rescheduled for next Saturday.',
      person: 'Nado',
    },
    {
      message:
        'My appointment for the doctor was rescheduled for next Saturday.',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
    {
      message:
        'Menus that are generated by the bottom app bar (such as a bottom',
      person: 'Nado',
    },
  ]

  const classes = useStyles()

  return (
    <React.Fragment>
      <Typography className={classes.text} variant="h5" gutterBottom>
        Chat
      </Typography>
      <List dense className={classes.list}>
        {messages.map(({ message, person }, index) => (
          <React.Fragment key={index}>
            <ListItem button>
              <ListItemText primary={person} secondary={message} />
            </ListItem>
          </React.Fragment>
        ))}
      </List>
    </React.Fragment>
  )
}
