import React, { Component } from './node_modules/react'

import { makeStyles } from './node_modules/@material-ui/core/styles'
import AppBar from './node_modules/@material-ui/core/AppBar'
import Toolbar from './node_modules/@material-ui/core/Toolbar'
import Typography from './node_modules/@material-ui/core/Typography'
import IconButton from './node_modules/@material-ui/core/IconButton'
import Paper from './node_modules/@material-ui/core/Paper'
import List from './node_modules/@material-ui/core/List'
import ListItem from './node_modules/@material-ui/core/ListItem'
import ListItemText from './node_modules/@material-ui/core/ListItemText'
import SearchIcon from './node_modules/@material-ui/icons/Search'
import MoreIcon from './node_modules/@material-ui/icons/MoreVert'

// import { HubConnection } from '@aspnet/signalr'
import * as signalR from './node_modules/@aspnet/signalr'

import axios from './node_modules/axios'

class Chat2 extends Component {
  constructor(props) {
    super(props)

    this.state = {
      nick: '',
      message: '',
        messages: [{ message= 'My appointment for the doctor was rescheduled for next Saturday.', person = "Nado" },
            { message= 'My appointment for the doctor was rescheduled for next Saturday.', person = "Nado" },
            { message= 'My appointment for the doctor was rescheduled for next Saturday.', person = "Nado" },
            { message= 'Menus that are generated by the bottom app bar (such as a bottom', person = "Nado"}],
      hubConnection: null,
    }
  }

  useStyles = makeStyles((theme) => ({
    text: {
      padding: theme.spacing(2, 2, 0),
    },
    paper: {
      paddingBottom: 50,
    },
    list: {
      marginBottom: theme.spacing(2),
    },
    appBar: {
      top: 'auto',
      bottom: 0,
    },
    grow: {
      flexGrow: 1,
    },
  }))

  classes = {}

  baseUrl = 'http://localhost:7071/api'

  componentDidMount = async () => {
    this.classes = this.useStyles()

    // let { data: info } = await axios.get(`${this.baseUrl}/negotiate`)

    // let options = {
    //   accessTokenFactory: () => info.accessToken,
    // }

    // this.hubConnection = new signalR.HubConnectionBuilder()
    //   .withUrl(info.url, options)
    //   .configureLogging(signalR.LogLevel.Information)
    //   .build()

    // this.hubConnection
    //   .start()
    //   .then(() => console.log('Connection started!'))
    //   .catch((err) => console.error(err.toString()))

    // this.hubConnection.on('ChatNotify', (receivedMessage) => {
    //   const messages = this.state.messages.concat([receivedMessage])
    //   this.setState({ messages })
    // })
  }

  sendMessage = () => {
    axios.post(
      `${this.baseUrl}/SendMessage`,
      `${this.state.nick}: ${this.state.message}`
    )
    this.setState({ message: '' })
  }

  render() {
    return (
      <div>
        <br />
        <input
          type="text"
          value={this.state.message}
          onChange={(e) => this.setState({ message: e.target.value })}
        />

        <button onClick={this.sendMessage}>Send</button>

        <div>
          {this.state.messages.map((message, index) => (
            <span style={{ display: 'block' }} key={index}>
              {' '}
              {message}{' '}
            </span>
          ))}
        </div>

        <React.Fragment>
          <Paper square className={this.classes.paper}>
            <Typography className={this.classes.text} variant="h5" gutterBottom>
              Chat
            </Typography>
            <List className={this.classes.list}>
              {this.state.messages.map(({ message, person }, index) => (
                <React.Fragment key={index}>
                  <ListItem button>
                    <ListItemText primary={message} secondary={person} />
                  </ListItem>
                </React.Fragment>
              ))}
            </List>
          </Paper>
          <AppBar
            position="fixed"
            color="primary"
            className={this.classes.appBar}
          >
            <Toolbar>
              <IconButton color="inherit">
                <SearchIcon />
              </IconButton>
              <IconButton edge="end" color="inherit">
                <MoreIcon />
              </IconButton>
            </Toolbar>
          </AppBar>
        </React.Fragment>
      </div>
    )
  }
}

export default Chat2
